export const initialNodes = [
    {
      id: '1',
      data: { label: 'Arrays & Hashing' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '2',
      data: { label: 'Two Pointers' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '3',
      data: { label: 'Stack' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '4',
      data: { label: 'Binary Search' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '5',
      data: { label: 'Sliding Window' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '6',
      data: { label: 'Linked List' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '7',
      data: { label: 'Trees' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '8',
      data: { label: 'Tries' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '9',
      data: { label: 'Heap / Priority Queue' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '10',
      data: { label: 'Backtracking' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '11',
      data: { label: 'Intervals' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '12',
      data: { label: 'Greedy' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '13',
      data: { label: 'Advanced Graphs' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '14',
      data: { label: 'Graphs' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '15',
      data: { label: '1-D DP' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '16',
      data: { label: '2-D DP' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '17',
      data: { label: 'Bit Manipulation' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
    {
      id: '18',
      data: { label: 'Math & Geometry' },
      type: 'custom',
      position: { x: 0, y: 0 },
    },
  ];
  
export const initialEdges = [
    { id: 'e1-2', source: '1', target: '2' },
    { id: 'e1-3', source: '1', target: '3' },
    { id: 'e2-3', source: '2', target: '6' },
    { id: 'e2-4', source: '2', target: '4' },
    { id: 'e2-5', source: '2', target: '5' },
    { id: 'e4-7', source: '4', target: '7' },
    { id: 'e6-7', source: '6', target: '7' },
    { id: 'e7-8', source: '7', target: '8' },
    { id: 'e7-9', source: '7', target: '9' },
    { id: 'e7-10', source: '7', target: '10' },
    { id: 'e9-11', source: '9', target: '11' },
    { id: 'e9-12', source: '9', target: '12' },
    { id: 'e9-13', source: '9', target: '13' },
    { id: 'e10-14', source: '10', target: '14' },
    { id: 'e14-13', source: '14', target: '13' },
    { id: 'e10-15', source: '10', target: '15' },
    { id: 'e14-16', source: '14', target: '16' },
    { id: 'e15-16', source: '15', target: '16' },
    { id: 'e14-18', source: '14', target: '18' },
    { id: 'e15-17', source: '15', target: '17' },
    { id: 'e17-18', source: '17', target: '18' },
  ];